apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dep
  labels:
    app: ecsdemo-nodejs
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecsdemo-nodejs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecsdemo-nodejs
    spec:
      containers:
      - image: ashwanijha04/angular:latest
        imagePullPolicy: Always
        name: angular
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-frontend
spec:
  selector:
    app: ecsdemo-nodejs
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
